=== mariocg5/AccesoDatos/Ejercicio08.iesjulianmarias.es/src/main/resources/EsquemaExamen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="examen" type="TipoExamen" />

	<xs:complexType name="TipoExamen">
		<xs:sequence>
			<xs:element name="autores" type="TipoAutores" minOccurs="1" maxOccurs="1" />
			<xs:element name="preguntas" type="TipoPreguntas" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TipoAutores">
		<xs:sequence>
			<xs:element name="autor" type="TipoAutor" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TipoPreguntas">
		<xs:sequence>
			<xs:element name="pregunta" type="TipoPregunta" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TipoAutor">
		<xs:sequence>
			<xs:element name="nombre" type="TipoCadenaCorta" minOccurs="1" maxOccurs="1" />
			<xs:element name="apellido1" type="TipoCadenaCorta" minOccurs="1" maxOccurs="1" />
			<xs:element name="apellido2" type="TipoCadenaCorta" minOccurs="1" maxOccurs="1" />
			<xs:element name="puesto" type="TipoCadenaLarga" minOccurs="1" maxOccurs="1" />
			<xs:element name="entidadTrabajo" type="TipoCadenaLarga" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="TipoAutoria" />
	</xs:complexType>

	<xs:complexType name="TipoPregunta">
		<xs:sequence>
			<xs:element name="enunciado" type="TipoCadenaLarga" minOccurs="1" maxOccurs="1" />
			<xs:element name="respuesta" type="TipoRespuesta" minOccurs="2" maxOccurs="4" />
		</xs:sequence>
		<xs:attribute name="dificultad" type="TipoDificultad" />
		<xs:attribute name="autoria" type="TipoAutoria" />
	</xs:complexType>

	<xs:complexType name="TipoRespuesta">
		<xs:simpleContent>
			<xs:extension base="TipoCadenaLarga">
				<xs:attribute name="validez" type="TipoBooleano" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:simpleType name="TipoCadenaCorta">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TipoCadenaLarga">
		<xs:restriction base="xs:string">
			<xs:maxLength value="300" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TipoDificultad">
		<xs:restriction base="xs:string">
			<xs:enumeration value="baja" />
			<xs:enumeration value="media" />
			<xs:enumeration value="alta" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TipoAutoria">
		<xs:restriction base="xs:string">
			<xs:pattern value="A[0-9]{1,3}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TipoBooleano">
		<xs:restriction base="xs:string">
			<xs:enumeration value="si" />
			<xs:enumeration value="no" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mariocg5/AccesoDatos/Ejercicio08.iesjulianmarias.es/src/main/resources/Ejercicio16 .xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<examen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation=".\EsquemaExamen.xsd">
    <autores>
        <autor id="A1">
            <nombre>Juan Antonio</nombre>
            <apellido1>García</apellido1>
            <apellido2>Pérez</apellido2>
            <puesto>Profesor titular</puesto>
            <entidadTrabajo>Universidad de Salamanca</entidadTrabajo>
        </autor>
        <autor id="A2">
            <nombre>Lucía</nombre>
            <apellido1>Alcántara</apellido1>
            <apellido2>Gómez</apellido2>
            <puesto>Profesor asociado</puesto>
            <entidadTrabajo>Universidad de Valladolid</entidadTrabajo>
        </autor>
        <autor id="A3">
            <nombre>Julia</nombre>
            <apellido1>Hernández</apellido1>
            <apellido2>Sánchez</apellido2>
            <puesto>Profesor titular</puesto>
            <entidadTrabajo>Universidad de Salamanca</entidadTrabajo>
        </autor>
    </autores>
    <preguntas>
        <pregunta autoria="A1" dificultad="baja">
            <enunciado>Indique qué definición de XML es correcta</enunciado>
            <respuesta validez="no">Es un lenguaje de programación</respuesta>
            <respuesta validez="si">Es un metalenguaje de etiquetado</respuesta>
            <respuesta validez="no">Es un procesaro de texto</respuesta>
            <respuesta validez="no">Es un tipo de base de datos</respuesta>
        </pregunta>
        <pregunta autoria="A1" dificultad="media">
            <enunciado>Para definir un atributo optativo en un DTD se usa:</enunciado>
            <respuesta validez="no">REQUIRED</respuesta>
            <respuesta validez="si">IMPLIED</respuesta>
            <respuesta validez="no">FIXED</respuesta>
            <respuesta validez="no">No se puede definir un atributo como optativo</respuesta>
        </pregunta>
        <pregunta autoria="A2" dificultad="alta">
            <enunciado>Los procesadores SAX y DOM son independientes del lenguaje de programación y existen versiones para Java, VisualBasic, C...</enunciado>
            <respuesta validez="si">Verdadero</respuesta>
            <respuesta validez="no">Falso</respuesta>
        </pregunta>
        <pregunta autoria="A2" dificultad="alta">
            <enunciado>Una sentencia try no puede estar dentro de un bloque de otra sentencia try</enunciado>
            <respuesta validez="no">Verdadero</respuesta>
            <respuesta validez="si">Falso</respuesta>
        </pregunta>
    </preguntas>
</examen>
